# Generated by Django 5.0.3 on 2024-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='package',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=100),
        ),
    ]
