# Generated by Django 5.0.3 on 2024-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bookings_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='package',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
