# Generated by Django 5.0.3 on 2024-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookings_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='package',
            field=models.CharField(choices=[('Nandi Betta', 'Nandi Betta - 900')], max_length=100),
        ),
    ]
